linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
  BorderZero:
    enabled: true
    convention: zero
  ColorKeyword:
    enabled: true
    severity: warning
  ColorVariable:
    enabled: true
  Comment:
    enabled: false
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: true
  DisableLinterReason:
    enabled: true
  DuplicateProperty:
    enabled: true
    ignore_consecutive:
      - font-size
  ElsePlacement:
    enabled: true
    style: same_line
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: false
  EmptyRule:
    enabled: true
  FinalNewline:
    enabled: true
    present: true
  HexLength:
    enabled: false
    style: short
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: true
  ImportantRule:
    enabled: true
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2
  LeadingZero:
    enabled: true
    style: include_zero
  LengthVariables:
    enabled: true
  MergeableSelector:
    enabled: true
    force_nesting: true
  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern
  NestingDepth:
    enabled: true
    max_depth: 3
    severity: warning
  PlaceholderInExtend:
    enabled: true
  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 10
  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    severity: warning
    separate_groups: false
  PropertySpelling:
    enabled: true
    extra_properties: []
  PseudoElement:
    enabled: true
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false
    severity: warning
  SelectorDepth:
    enabled: true
    max_depth: 2
    severity: warning
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 4]
    severity: warning
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterComment:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterVariableColon:
    enabled: false
  SpaceAfterVariableName:
    enabled: true
  SpaceAroundOperator:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false
  SpaceBetweenParens:
    enabled: true
    spaces: 0
  StringQuotes:
    enabled: true
    style: single_quotes
  TrailingSemicolon:
    enabled: true
  TrailingWhitespace:
    enabled: true
  TrailingZero:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VariableForProperty:
    enabled: true
    properties:
      - color
      - font
  VendorPrefixes:
    enabled: true
    identifier_list: bourbon
    include: []
    exclude: []
  ZeroUnit:
    enabled: true
    severity: warning
